#Window size setup and Frame rate
WINDOW_HEIGHT = 512
WINDOW_WIDTH = 288
BACKGROUND_MULTIPLIER = 1.5
WINDOW_SIZE = (WINDOW_WIDTH * BACKGROUND_MULTIPLIER, WINDOW_HEIGHT * BACKGROUND_MULTIPLIER)
FRAME_RATE = 120
